### ISSUE TITLE
Add hyperlink to updated 2019 data?

### ISSUE THREAD

**Issue by LawrenceHecht** [cncf/velocity#18]
I saw the latest chart in this tweet: https://twitter.com/dankohn1/status/1148967017048924162.

Will there be an easy to access spreadsheet like a few years ago? (see https://docs.google.com/spreadsheets/d/1a2VdKfAI1g9ZyWL09TnJ-snOpi4BC9kaEVmB7IufY7g/edit#gid=1169691230)

Lukas, I have been going through all your work. You are doing a great job of documenting everything, I just know that I'm less likely to use the data if I have to sift through everything.,

**Comment by lukaszgryglicki** [comment]
Hyperlink is there: https://github.com/cncf/velocity/blob/master/docs/top30_chart_creation.md#in-short
You have to request access for it or eventually, @dankohn can let me make that chart public.

**Comment by dankohn** [comment]
It is now public.
