### ISSUE TITLE
Data for 2020?

### ISSUE THREAD

**Issue by vsoch** [cncf/velocity#19]
Hey CNCF velocity! I was wondering if there was a plan to generate new data for 2019-2020? It would be really great to see!

**Comment by lukaszgryglicki** [comment]
I think such data was already generated:
- [Top 30 open source projects 1/1/20 - 1/1/21](https://docs.google.com/spreadsheets/d/1D4qyRAOC57HV7xuEG_ngdEJBlt8Lztl50ziut0elBgw/edit?usp=sharing).
- [Top 30 open source projects 1/1/19 - 1/1/20](https://docs.google.com/spreadsheets/d/1R9nAoL6Av62rpB5LvXyZvYTL2YaC0gpnxMrabmsr9AU/edit?usp=sharing).
- [LF Projects 1/1/20 - 1/1/21](https://docs.google.com/spreadsheets/d/1euHQvzKxeloZF2IQ8O1G_NkfXCGH35ExXIAgxHxiyxU/edit?usp=sharing).
- [LF Projects 1/1/19 - 1/1/20](https://docs.google.com/spreadsheets/d/12mWSokd7jH_HFV1aQC1kK4DQ2YUlWt4cWI5YKE_7XoM/edit?usp=sharing).
- [CNCF Projects 1/1/20 - 1/1/21](https://docs.google.com/spreadsheets/d/1L-Msl6RH33RlOWk0yA80bo64WLKsgnDUlmlphtxHxZo/edit?usp=sharing).
- [CNCF Projects 2/1/19 - 2/1/20](https://docs.google.com/spreadsheets/d/18ceM03XcbuVi7pd4qdb8-aWvnc58qxtE5F7p14XbVA0/edit?usp=sharing).

**Comment by vsoch** [comment]
Thank you! It looks like the second, fourth, and sixth are yet to be made publicly accessible? 

@tgamblin

**Comment by lukaszgryglicki** [comment]
Permissions updated.
