### ISSUE TITLE
velocity_x and animator causing error while trying to run flutter project

### ISSUE THREAD

**Issue by Rafien** [cncf/velocity#20]
I started a project today, i want to do a form with flutter + dart and have seen that velocity_x looks interesting for front so i add its last version to my pubspec.yaml in VSC and 'flutter pub get' it.

Then i import it to my dart code and start running it.

Ended up with this error and am just starting dart so don't really know how to fix it.

![image](https://user-images.githubusercontent.com/25200873/122404922-e97cd280-cf7f-11eb-9003-66d626b75e7a.png)

**Comment by lukaszgryglicki** [comment]
Hmmm, this seems unrelated to `cncf/velocity` ...

**Comment by Rafien** [comment]
> Hmmm, this seems unrelated to `cncf/velocity` ...

mb someone gave me the wrong link
