### ISSUE TITLE
Sigstore is missing from the list

### ISSUE THREAD

**Issue by dlorenc** [cncf/velocity#23]
I took a look at the LF projects velocity sheet: https://docs.google.com/spreadsheets/d/1XWFyDLi299Wb-PVWE7s9MpFGN9SDGQOmUUc4VgVVuK8/edit#gid=1169691230

and Sigstore is missing. Any idea how to get it added? We're at github.com/sigstore, and have been an LF project since early 2021.

**Comment by caniszczyk** [comment]
@lukaszgryglicki can you pull the data again and include sigstore as one of the projects

Also I noticed a mistake where spinnaker should also pull in the https://github.com/spinnaker/spinnaker repo which has the majority authors, it seems we are only pulling spinnaker.io,governance

**Comment by dlorenc** [comment]
Thanks! If there's a file to edit or set of steps I can do I'm happy to help!

**Comment by lukaszgryglicki** [comment]
I will add them, actually, I don't have any source for the complete LF projects list, so we can miss more LF projects - please let me know if any other LF projects are missing.

**Comment by lukaszgryglicki** [comment]
For Spinnaker we already track all public reports from `spinnaker` org - but will double check this now.

**Comment by lukaszgryglicki** [comment]
Charts updated (7/7/21 - now & 1/1/21 - now), both include Sigstore and also fixed `spinnaker/spinnaker` (it was excluded by mistake.

**Comment by caniszczyk** [comment]
Thanks!

**Comment by dlorenc** [comment]
Thanks for this!
