### ISSUE TITLE
Ensure that forked repos don't end up in velocity reports

### ISSUE THREAD

**Issue by caniszczyk** [cncf/velocity#25]
For example, in the latest velocity report that we haven't published, the Cilium projects included a forked repo of Linux which jacks up the velocity data imho, we should probably ignore all FORKED repos into the project, e.g,. https://github.com/cilium/linux

**Comment by caniszczyk** [comment]
current repos for cilium which the community pointed out linux is part of: 

cilium+ebpf+cilium-cli+tetragon+cilium.io+hubble+packer-ci-build+hubble-ui+pwru+ebpf.io-summit+image-tools+certgen+cilium-olm+hubble-otel+cilium-service-mesh-beta+proxy+release+linux+charts+scaffolding+ebpf.io+ci-kernels+ubuntu-curl+alpine-curl+json-mock+sphinx_rtd_theme+github-actions+workerpool+installfest+docsearch-scraper-webhook+certified-operators+team-manager+openshift-terraform-upi+iproute2+fake+metallb+cilium-sysdump+.github+coverbee+kustomize-bases+lumberjack+libbpf+cilium-perf-networking+istio+graceful-termination-test-apps+cilium-etcd-operator+redhat-marketplace-operators+little-vm-helper+dns+hubble-export-stdout+echoserver+scruffy+chaos-testing-examples+migrate-svc-test+echoserver-udp+affinity-test-apps+xdp-config+helm-toolbox+starwars-docker+kubenetbench+chaos-monkeys+bpf-map+certification-releases

**Comment by lukaszgryglicki** [comment]
Fixing all reports with: https://github.com/cncf/velocity/commit/cebbb88ea55e0f4e81863caa21b49f5d5d9a4ab9

**Comment by lukaszgryglicki** [comment]
Also in: https://github.com/cncf/devstats-reports/commit/485ba194d665dd2703435bc9f3070f635d4b610d, https://github.com/cncf/devstats-reports/commit/11d225fc7942f747931664596e22639cd61425fe, https://github.com/cncf/devstats-docker-images/commit/dd64bd62c91616de01d6859bbc83f26c14d92d48, https://github.com/cncf/devstats-docker-images/commit/e46e347faa2483e11aa850acdd5098879f713413

**Comment by lukaszgryglicki** [comment]
All is fixed now.
