### ISSUE TITLE
Fix  Chart Title in Google Sheets

### ISSUE THREAD

**Issue by LawrenceHecht** [cncf/velocity#26]
The "Chart" sheet in for the "Top 30 projects" Google workbooks reads "Top 20" and needs to be fixed. 

For example: https://docs.google.com/spreadsheets/d/124e8u53eq-zCPPnA3ICe0LIPkOmVlxakMmka_8t9w_A/edit#gid=134798507

I had requested "edit" access to fix this. I don't need that access if someone addresses this issue.

**Comment by lukaszgryglicki** [comment]
Done.

**Comment by Ligoml** [comment]
I find the same issue in this sheet: https://docs.google.com/spreadsheets/d/1bQ8hLa34RTeFlRCIZLQekw3hrjWygJhPmPwnWPeTq8A/edit#gid=134798507

**Comment by lukaszgryglicki** [comment]
Done.
