### ISSUE TITLE
Add Yocto Project for velocity statistics

### ISSUE THREAD

**Issue by rpurdie** [cncf/velocity#27]
I wondered if it would be possible to add Yocto Project to the list of LF projects? Someone mentioned to me that it wasn't listed but it is a key LF project.

Whilst our repos are at git.yoctoproject.org, we do have a github mirror for poky, one of our main repos here: https://github.com/yoctoproject/poky

For issues, we bugzilla at https://bugzilla.yoctoproject.org

**Comment by lukaszgryglicki** [comment]
We track GitHub using BigQuery, it would be hard to tack anything else.
If you have public GitHub org(s), repos(s) I can add them.
If I need to track somethgn else manually, then I need to know number of the following metrics per given (next) report date range (prbably that would be 1/1/22 - 1/1/23):
- activity (on GtHub this is just all activity, probably we can skip this, but I do have that for other projects).
- comments (or similar activity on issues/tickets/emails whatever).
- prs (or simlar like merge requests, etc.).
- commits (or similar like changesets ec.)
- issues (or similar, like tickets etc.)
- authors (number of distinct people cntributing).
- pushes (rather optional, we can skip it, other projects have it)

Additionally I need
- project name (Yocto: ok).
- project URL
- list of orgs (if I can track them on GitHub).
- list of repos (if I can track them on GitHub).

If you @rpurdie can provide tha data for the next report (say around the beginning of Jan 2023) I can add itmanually.
cc @caniszczyk

**Comment by rpurdie** [comment]
Project Name: "Yocto Project"
Project url: https://www.yoctoproject.org/
List of orgs on github: "yoctoproject" and "openembedded"
Repos: I'd suggest "bitbake", "openembedded-core", "meta-openembedded" from the openembedded org.

"poky" from yoctoproject is a combined version of some of the others above so would probably just confuse the stats.

I'd suggest that the data from those three repos is probably good enough to give us an entry in the table. Since we handle issues externally in bugzilla we can probably just ignore those for now.

**Comment by rpurdie** [comment]
> OK, I will keep this open and add to my TODO ist for the next report.

Thanks! If you need any other information let me know.

**Comment by lukaszgryglicki** [comment]
I'm generating reports, I'll include Yocto data in 2022 year version - ETA is this or next week.
cc @caniszczyk @rpurdie

**Comment by rpurdie** [comment]
Thanks, very much appreciated!
