### ISSUE TITLE
See project velocity by year

### ISSUE THREAD

**Issue by xmulligan** [cncf/velocity#28]
The velocity reports are great, but they bias towards older projects because they just look at absolute numbers. Would it be possible to add a time dimension to the velocity reports so we can see  which projects are speeding up or slowing down?

**Comment by lukaszgryglicki** [comment]
They get statistics for the selected time range (like 1/1/22 - 1/1/23) so they don't include dfata from before 1/1/22 - not sure what exactly do you mean?
There is no slow down/speed up metric becaus ethat would require comparing previous year report with current one.
This can be done by combining two reports, say for 2022 and 2023 - for each project we could get current `(year/previous year)*100%` or somethig similar to see velocity change between 2022 and 2023 (this can be per any arbitrary metric or all metrics combined).

That would require @caniszczyk to approve this kind of extra work and allowing me to work on it (I have other projects too, especially under LF).

**Comment by xmulligan** [comment]
Ahh sorry, I didn't realize this was just the data from one year. It would still be cool to see how it changes across years.

**Comment by lukaszgryglicki** [comment]
Np but this needs approval @caniszczyk so I can work on this on some days (and not working on LF tasks at the same time,w hich also needs approval).

**Comment by onlydole** [comment]
+1 to these views, even being able to filter by CNCF Landscape category and subcategory (ex. Runtime & Cloud Native Storage) would be enlightening.

**Comment by xmulligan** [comment]
Is this still interesting or should I close the issue?
