### ISSUE TITLE
Date in velocity charts title is incorrect

### ISSUE THREAD

**Issue by lizrice** [cncf/velocity#31]
If you open any of the charts for CNCF Project Velocity, the date in the chart title seems to be hard-coded to "1/1/2022 - 1/1/2023", which doesn't match the title of the spreadsheet. I think the spreadsheet title is correct - for example, this is the current report which seems to be correctly showing the last year from 12 October 2022

<img width="385" alt="Screenshot 2023-10-20 at 10 12 06" src="https://github.com/cncf/velocity/assets/458616/fdfd7ec2-e1a4-46c4-a463-bd346f0a26c9">

**Comment by lukaszgryglicki** [comment]
Will update, thanks for reporting. I just forgot chart titles.

**Comment by lukaszgryglicki** [comment]
This is fixed, thanks for reporting.

**Comment by lizrice** [comment]
So fast! Thank you
