### ISSUE TITLE
Zephyr duplicated in 1/1/2023-1/1/2024 Linux Foundation data

### ISSUE THREAD

**Issue by e3b0c442** [cncf/velocity#34]
Hello,

Zephyr is represented twice in the 1/1/2023-1/1/2024 Linux Foundation Projects data/chart. Also, OpenTelemetry seems to be missing from that chart.

It appears that the OpenTelemetry data may have been subsumed by one of those Zephyr entries.

**Comment by lukaszgryglicki** [comment]
I'll take a look on Friday or Monday, thanks for reporting.

**Comment by lukaszgryglicki** [comment]
Fixed, thanks for reporting @e3b0c442
