### ISSUE TITLE
All Academy Software Foundation projects grouped together - likely should be seperated.

### ISSUE THREAD

**Issue by jmertic** [cncf/velocity#37]
Hi! All the Academy Software Foundation projects are grouped together. To be similar to other LF projects on how velocity is calculated, they should be seperated. What would be the best way to do this? Thanks!

**Comment by lukaszgryglicki** [comment]
The best way would be to specify each project and list of its GitHub repos and then I will split them all according to this with the next report (about January 2025) or even create a new report for this if this is urgent and approved by @caniszczyk

**Comment by lukaszgryglicki** [comment]
@jmertic friendly ping.

**Comment by jmertic** [comment]
Sure can! Where would the best way to communicate that to you be? I have a CSV file, if that would work.

**Comment by lukaszgryglicki** [comment]
CSV is great, just upload it somewhere so I can download and update.
Do you want me to regenerate LFR report now, or it can wait till another (normal) round which will be in January?
cc @caniszczyk

**Comment by caniszczyk** [comment]
Let’s wait for the next refresh

Cheers,

Chris Aniszczyk
https://aniszczyk.org

**Comment by lukaszgryglicki** [comment]
OK, so I'm waiting for the CSV file to update config.

**Comment by jmertic** [comment]
Here you go! Let me know if this works for you.

[ASWF repo and project mappings.csv](https://github.com/user-attachments/files/16413052/ASWF.repo.and.project.mappings.csv)

**Comment by lukaszgryglicki** [comment]
Works for me, I'll update the config on Friday. Thanks.

**Comment by lukaszgryglicki** [comment]
This is done and https://docs.google.com/spreadsheets/d/1Aiyb2qoQ-vgTXkP3F5OdSB8nrVI43Al0EJfkkZjRqqY/edit?usp=sharing is updated. I've prefixed project names with `ASWF ` because some had too generic names.

**Comment by jmertic** [comment]
Awesome - thank you!
