### ISSUE TITLE
PyTorch as a LF project?

### ISSUE THREAD

**Issue by cjyabraham** [cncf/velocity#38]
Shouldn't [PyTorch](https://pytorch.org/) be listed on the [LF Projects sheet](https://docs.google.com/spreadsheets/d/1Aiyb2qoQ-vgTXkP3F5OdSB8nrVI43Al0EJfkkZjRqqY/edit?gid=1169691230#gid=1169691230)?

**Comment by lukaszgryglicki** [comment]
I don't know. Should it?

**Comment by cjyabraham** [comment]
[I think so](https://pytorch.org/foundation#:~:text=As%20part%20of%20The%20Linux%20Foundation).

**Comment by lukaszgryglicki** [comment]
I'm not sure who can confirm this - I can add this anytime, cc maybe @caniszczyk ?

**Comment by caniszczyk** [comment]
Yes PyTorch is an LF project. Please regenerate this report

Cheers,

Chris Aniszczyk
https://aniszczyk.org

**Comment by lukaszgryglicki** [comment]
Ok so will do this together with ASWF update on Friday.
